version: '2.0'
services:
  api-hubspot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    ports:
      - "9002:80"
    environment:
      APP_NAME: api-hubspot
      APP_ENV: local
      APP_KEY: base64:jV6rKjzcoeM1nUKduZt2P1SgiMrro0zCxfMfOHEwZEA=
      APP_DEBUG: true
      APP_URL: http://localhost
      APP_TIMEZONE: UTC
      LOG_CHANNEL: stack
      LOG_SLACK_WEBHOOK_URL:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: klaxen_audeed
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_SQL_HOST: 10.1.7.3
      DB_SQL_PORT: 1433
      DB_SQL_DATABASE: MAXWEST
      DB_SQL_USERNAME: Max_informes
      DB_SQL_PASSWORD: Secur0912
      CACHE_DRIVER: file
      QUEUE_CONNECTION: sync
      HUBSPOT_BR: 3HuY0Be2yP8YPHhl4n5uaSJlqgSuajMtHP8t6WhMOawJ6Xjpzkqp74V0B99fw3st
