name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  update-repo:
    runs-on: self-hosted
    steps:
      # Accede al contenedor y actualiza el repositorio
      - name: Acceso al contenedor y pull
        run: |
          docker exec -u root -it api-hubspot-api-hubspot-1 /bin/sh -c '
            cd /var/www &&
            git pull origin main &&
            echo Git Pull completado dentro del contenedor
          '
